<?php
/**
 * HistoricIdentityLinkLogApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0-alpha2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * HistoricIdentityLinkLogApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class HistoricIdentityLinkLogApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getHistoricIdentityLinks
     *
     * Get Identity Link Logs
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     * @param  string $sort_by Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)
     * @param  string $sort_order Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)
     * @param  int $first_result Pagination of results. Specifies the index of the first result to return. (optional)
     * @param  int $max_results Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]|\OpenAPI\Client\Model\ExceptionDto
     */
    public function getHistoricIdentityLinks($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null, $sort_by = null, $sort_order = null, $first_result = null, $max_results = null)
    {
        list($response) = $this->getHistoricIdentityLinksWithHttpInfo($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id, $sort_by, $sort_order, $first_result, $max_results);
        return $response;
    }

    /**
     * Operation getHistoricIdentityLinksWithHttpInfo
     *
     * Get Identity Link Logs
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     * @param  string $sort_by Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)
     * @param  string $sort_order Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)
     * @param  int $first_result Pagination of results. Specifies the index of the first result to return. (optional)
     * @param  int $max_results Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]|\OpenAPI\Client\Model\ExceptionDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHistoricIdentityLinksWithHttpInfo($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null, $sort_by = null, $sort_order = null, $first_result = null, $max_results = null)
    {
        $request = $this->getHistoricIdentityLinksRequest($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id, $sort_by, $sort_order, $first_result, $max_results);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\ExceptionDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ExceptionDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHistoricIdentityLinksAsync
     *
     * Get Identity Link Logs
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     * @param  string $sort_by Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)
     * @param  string $sort_order Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)
     * @param  int $first_result Pagination of results. Specifies the index of the first result to return. (optional)
     * @param  int $max_results Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistoricIdentityLinksAsync($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null, $sort_by = null, $sort_order = null, $first_result = null, $max_results = null)
    {
        return $this->getHistoricIdentityLinksAsyncWithHttpInfo($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id, $sort_by, $sort_order, $first_result, $max_results)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHistoricIdentityLinksAsyncWithHttpInfo
     *
     * Get Identity Link Logs
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     * @param  string $sort_by Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)
     * @param  string $sort_order Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)
     * @param  int $first_result Pagination of results. Specifies the index of the first result to return. (optional)
     * @param  int $max_results Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistoricIdentityLinksAsyncWithHttpInfo($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null, $sort_by = null, $sort_order = null, $first_result = null, $max_results = null)
    {
        $returnType = '\OpenAPI\Client\Model\HistoricIdentityLinkLogDto[]';
        $request = $this->getHistoricIdentityLinksRequest($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id, $sort_by, $sort_order, $first_result, $max_results);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHistoricIdentityLinks'
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     * @param  string $sort_by Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter. (optional)
     * @param  string $sort_order Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter. (optional)
     * @param  int $first_result Pagination of results. Specifies the index of the first result to return. (optional)
     * @param  int $max_results Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getHistoricIdentityLinksRequest($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null, $sort_by = null, $sort_order = null, $first_result = null, $max_results = null)
    {

        $resourcePath = '/history/identity-link-log';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($type !== null) {
            if('form' === 'form' && is_array($type)) {
                foreach($type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['type'] = $type;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }
        // query params
        if ($group_id !== null) {
            if('form' === 'form' && is_array($group_id)) {
                foreach($group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['groupId'] = $group_id;
            }
        }
        // query params
        if ($date_before !== null) {
            if('form' === 'form' && is_array($date_before)) {
                foreach($date_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['dateBefore'] = $date_before;
            }
        }
        // query params
        if ($date_after !== null) {
            if('form' === 'form' && is_array($date_after)) {
                foreach($date_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['dateAfter'] = $date_after;
            }
        }
        // query params
        if ($task_id !== null) {
            if('form' === 'form' && is_array($task_id)) {
                foreach($task_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['taskId'] = $task_id;
            }
        }
        // query params
        if ($process_definition_id !== null) {
            if('form' === 'form' && is_array($process_definition_id)) {
                foreach($process_definition_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['processDefinitionId'] = $process_definition_id;
            }
        }
        // query params
        if ($process_definition_key !== null) {
            if('form' === 'form' && is_array($process_definition_key)) {
                foreach($process_definition_key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['processDefinitionKey'] = $process_definition_key;
            }
        }
        // query params
        if ($operation_type !== null) {
            if('form' === 'form' && is_array($operation_type)) {
                foreach($operation_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['operationType'] = $operation_type;
            }
        }
        // query params
        if ($assigner_id !== null) {
            if('form' === 'form' && is_array($assigner_id)) {
                foreach($assigner_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['assignerId'] = $assigner_id;
            }
        }
        // query params
        if ($tenant_id_in !== null) {
            if('form' === 'form' && is_array($tenant_id_in)) {
                foreach($tenant_id_in as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantIdIn'] = $tenant_id_in;
            }
        }
        // query params
        if ($without_tenant_id !== null) {
            if('form' === 'form' && is_array($without_tenant_id)) {
                foreach($without_tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['withoutTenantId'] = $without_tenant_id;
            }
        }
        // query params
        if ($sort_by !== null) {
            if('form' === 'form' && is_array($sort_by)) {
                foreach($sort_by as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sortBy'] = $sort_by;
            }
        }
        // query params
        if ($sort_order !== null) {
            if('form' === 'form' && is_array($sort_order)) {
                foreach($sort_order as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['sortOrder'] = $sort_order;
            }
        }
        // query params
        if ($first_result !== null) {
            if('form' === 'form' && is_array($first_result)) {
                foreach($first_result as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['firstResult'] = $first_result;
            }
        }
        // query params
        if ($max_results !== null) {
            if('form' === 'form' && is_array($max_results)) {
                foreach($max_results as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['maxResults'] = $max_results;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getHistoricIdentityLinksCount
     *
     * Get Identity Link Log Count
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\CountResultDto|\OpenAPI\Client\Model\ExceptionDto
     */
    public function getHistoricIdentityLinksCount($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null)
    {
        list($response) = $this->getHistoricIdentityLinksCountWithHttpInfo($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id);
        return $response;
    }

    /**
     * Operation getHistoricIdentityLinksCountWithHttpInfo
     *
     * Get Identity Link Log Count
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\CountResultDto|\OpenAPI\Client\Model\ExceptionDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function getHistoricIdentityLinksCountWithHttpInfo($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null)
    {
        $request = $this->getHistoricIdentityLinksCountRequest($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\CountResultDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\CountResultDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Model\ExceptionDto' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\ExceptionDto', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\CountResultDto';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\CountResultDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ExceptionDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getHistoricIdentityLinksCountAsync
     *
     * Get Identity Link Log Count
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistoricIdentityLinksCountAsync($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null)
    {
        return $this->getHistoricIdentityLinksCountAsyncWithHttpInfo($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getHistoricIdentityLinksCountAsyncWithHttpInfo
     *
     * Get Identity Link Log Count
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getHistoricIdentityLinksCountAsyncWithHttpInfo($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null)
    {
        $returnType = '\OpenAPI\Client\Model\CountResultDto';
        $request = $this->getHistoricIdentityLinksCountRequest($type, $user_id, $group_id, $date_before, $date_after, $task_id, $process_definition_id, $process_definition_key, $operation_type, $assigner_id, $tenant_id_in, $without_tenant_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getHistoricIdentityLinksCount'
     *
     * @param  string $type Restricts to identity links that have the given type (candidate/assignee/owner). (optional)
     * @param  string $user_id Restricts to identity links that have the given user id. (optional)
     * @param  string $group_id Restricts to identity links that have the given group id. (optional)
     * @param  \DateTime $date_before Restricts to identity links that have the time before the given time. (optional)
     * @param  \DateTime $date_after Restricts to identity links that have the time after the given time. (optional)
     * @param  string $task_id Restricts to identity links that have the given task id. (optional)
     * @param  string $process_definition_id Restricts to identity links that have the given process definition id. (optional)
     * @param  string $process_definition_key Restricts to identity links that have the given process definition key. (optional)
     * @param  string $operation_type Restricts to identity links that have the given operationType (add/delete). (optional)
     * @param  string $assigner_id Restricts to identity links that have the given assigner id. (optional)
     * @param  string $tenant_id_in Filter by a comma-separated list of tenant ids. (optional)
     * @param  bool $without_tenant_id Only include historic identity links that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getHistoricIdentityLinksCountRequest($type = null, $user_id = null, $group_id = null, $date_before = null, $date_after = null, $task_id = null, $process_definition_id = null, $process_definition_key = null, $operation_type = null, $assigner_id = null, $tenant_id_in = null, $without_tenant_id = null)
    {

        $resourcePath = '/history/identity-link-log/count';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($type !== null) {
            if('form' === 'form' && is_array($type)) {
                foreach($type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['type'] = $type;
            }
        }
        // query params
        if ($user_id !== null) {
            if('form' === 'form' && is_array($user_id)) {
                foreach($user_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['userId'] = $user_id;
            }
        }
        // query params
        if ($group_id !== null) {
            if('form' === 'form' && is_array($group_id)) {
                foreach($group_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['groupId'] = $group_id;
            }
        }
        // query params
        if ($date_before !== null) {
            if('form' === 'form' && is_array($date_before)) {
                foreach($date_before as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['dateBefore'] = $date_before;
            }
        }
        // query params
        if ($date_after !== null) {
            if('form' === 'form' && is_array($date_after)) {
                foreach($date_after as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['dateAfter'] = $date_after;
            }
        }
        // query params
        if ($task_id !== null) {
            if('form' === 'form' && is_array($task_id)) {
                foreach($task_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['taskId'] = $task_id;
            }
        }
        // query params
        if ($process_definition_id !== null) {
            if('form' === 'form' && is_array($process_definition_id)) {
                foreach($process_definition_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['processDefinitionId'] = $process_definition_id;
            }
        }
        // query params
        if ($process_definition_key !== null) {
            if('form' === 'form' && is_array($process_definition_key)) {
                foreach($process_definition_key as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['processDefinitionKey'] = $process_definition_key;
            }
        }
        // query params
        if ($operation_type !== null) {
            if('form' === 'form' && is_array($operation_type)) {
                foreach($operation_type as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['operationType'] = $operation_type;
            }
        }
        // query params
        if ($assigner_id !== null) {
            if('form' === 'form' && is_array($assigner_id)) {
                foreach($assigner_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['assignerId'] = $assigner_id;
            }
        }
        // query params
        if ($tenant_id_in !== null) {
            if('form' === 'form' && is_array($tenant_id_in)) {
                foreach($tenant_id_in as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['tenantIdIn'] = $tenant_id_in;
            }
        }
        // query params
        if ($without_tenant_id !== null) {
            if('form' === 'form' && is_array($without_tenant_id)) {
                foreach($without_tenant_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['withoutTenantId'] = $without_tenant_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
