<?php
/**
 * DeploymentWithDefinitionsDtoAllOfTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.15.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DeploymentWithDefinitionsDtoAllOfTest Class Doc Comment
 *
 * @category    Class
 * @description DeploymentWithDefinitionsDtoAllOf
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DeploymentWithDefinitionsDtoAllOfTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DeploymentWithDefinitionsDtoAllOf"
     */
    public function testDeploymentWithDefinitionsDtoAllOf()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deployed_process_definitions"
     */
    public function testPropertyDeployedProcessDefinitions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deployed_decision_definitions"
     */
    public function testPropertyDeployedDecisionDefinitions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deployed_decision_requirements_definitions"
     */
    public function testPropertyDeployedDecisionRequirementsDefinitions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deployed_case_definitions"
     */
    public function testPropertyDeployedCaseDefinitions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
