<?php
/**
 * ExecutionApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.15.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExecutionApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExecutionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createIncident
     *
     * Create Incident.
     *
     */
    public function testCreateIncident()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteLocalExecutionVariable
     *
     * Delete Local Execution Variable.
     *
     */
    public function testDeleteLocalExecutionVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExecution
     *
     * Get Execution.
     *
     */
    public function testGetExecution()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExecutions
     *
     * Get Executions.
     *
     */
    public function testGetExecutions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getExecutionsCount
     *
     * Get Execution Count.
     *
     */
    public function testGetExecutionsCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLocalExecutionVariable
     *
     * Get Local Execution Variable.
     *
     */
    public function testGetLocalExecutionVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLocalExecutionVariableBinary
     *
     * Get Local Execution Variable (Binary).
     *
     */
    public function testGetLocalExecutionVariableBinary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLocalExecutionVariables
     *
     * Get Local Execution Variables.
     *
     */
    public function testGetLocalExecutionVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMessageEventSubscription
     *
     * Get Message Event Subscription.
     *
     */
    public function testGetMessageEventSubscription()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifyLocalExecutionVariables
     *
     * Update/Delete Local Execution Variables.
     *
     */
    public function testModifyLocalExecutionVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putLocalExecutionVariable
     *
     * Put Local Execution Variable.
     *
     */
    public function testPutLocalExecutionVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queryExecutions
     *
     * Get Executions (POST).
     *
     */
    public function testQueryExecutions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for queryExecutionsCount
     *
     * Get Execution Count (POST).
     *
     */
    public function testQueryExecutionsCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setLocalExecutionVariableBinary
     *
     * Post Local Execution Variable (Binary).
     *
     */
    public function testSetLocalExecutionVariableBinary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for signalExecution
     *
     * Trigger Execution.
     *
     */
    public function testSignalExecution()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for triggerEvent
     *
     * Trigger Message Event Subscription.
     *
     */
    public function testTriggerEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
