<?php
/**
 * TaskLocalVariableApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.15.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaskLocalVariableApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaskLocalVariableApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteTaskLocalVariable
     *
     * Delete Local Task Variable.
     *
     */
    public function testDeleteTaskLocalVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskLocalVariable
     *
     * Get Local Task Variable.
     *
     */
    public function testGetTaskLocalVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskLocalVariableBinary
     *
     * Get Local Task Variable (Binary).
     *
     */
    public function testGetTaskLocalVariableBinary()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTaskLocalVariables
     *
     * Get Local Task Variables.
     *
     */
    public function testGetTaskLocalVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for modifyTaskLocalVariables
     *
     * Update/Delete Local Task Variables.
     *
     */
    public function testModifyTaskLocalVariables()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putTaskLocalVariable
     *
     * Update Local Task Variable.
     *
     */
    public function testPutTaskLocalVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setBinaryTaskLocalVariable
     *
     * Update Local Task Variable (Binary).
     *
     */
    public function testSetBinaryTaskLocalVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
